### ISSUE TITLE
Transforms used

### ISSUE THREAD

**Issue by ThomasNorr** [NehaKalibhat/falcon-explain#2]
Hello,

thanks again for your fascinating work and fixing my last issue.
I am now wondering if there is a reason why the grad cam in get_interpretable_features.py and clip take the same image, so after the same set of transformations.
As far as I can see, the transformation used is different to the transformation used by clip.

Greetings

**Comment by NehaKalibhat** [comment]
Thanks for bringing this up. Do you mean the default transform list in CLIP - https://github.com/openai/CLIP/blob/a1d071733d7111c9c014f024669f959182114e33/clip/clip.py#L79

We did use the CLIP transform in our paper results, however we don't see a major difference in results using the transform we have set up.

**Comment by ThomasNorr** [comment]
Alright, thanks for the answer.
Yes, I meant those provided by openai and returned by clip.load().
Since the differences are so small, similar results make sense.
However, true to the method would be using the original clip transform, right?

**Comment by NehaKalibhat** [comment]
Yes. I'll check in the CLIP transform usage shortly.
